apiVersion: v1
kind: Namespace
metadata:
  name: supabase
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: supabase
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:13
          env:
            - name: POSTGRES_PASSWORD
              value: supersecret
            - name: POSTGRES_DB
              value: postgres
          ports:
            - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: supabase
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
