apiVersion: v1
kind: Namespace
metadata:
  name: supabase
---
# PostgreSQL
apiVersion: apps/v1
kind: Deployment
metadata:
  name: supabase-postgres
  namespace: supabase
spec:
  replicas: 1
  selector:
    matchLabels:
      app: supabase-postgres
  template:
    metadata:
      labels:
        app: supabase-postgres
    spec:
      containers:
        - name: postgres
          image: supabase/postgres:15.1.0.118
          env:
            - name: POSTGRES_PASSWORD
              value: supersecret
            - name: POSTGRES_DB
              value: postgres
          ports:
            - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: supabase-postgres
  namespace: supabase
spec:
  selector:
    app: supabase-postgres
  ports:
    - port: 5432
      targetPort: 5432
---
# Auth
apiVersion: apps/v1
kind: Deployment
metadata:
  name: supabase-auth
  namespace: supabase
spec:
  replicas: 1
  selector:
    matchLabels:
      app: supabase-auth
  template:
    metadata:
      labels:
        app: supabase-auth
    spec:
      containers:
        - name: auth
          image: supabase/gotrue:v2.59.3
          env:
            - name: GOTRUE_DB_DRIVER
              value: postgres
            - name: GOTRUE_DB_DATABASE_URL
              value: postgres://postgres:supersecret@supabase-postgres:5432/postgres
            - name: GOTRUE_SITE_URL
              value: http://localhost:9999
            - name: GOTRUE_JWT_SECRET
              value: supersecretjwt
          ports:
            - containerPort: 9999
---
apiVersion: v1
kind: Service
metadata:
  name: supabase-auth
  namespace: supabase
spec:
  selector:
    app: supabase-auth
  ports:
    - port: 9999
      targetPort: 9999
---
# Studio
apiVersion: apps/v1
kind: Deployment
metadata:
  name: supabase-studio
  namespace: supabase
spec:
  replicas: 1
  selector:
    matchLabels:
      app: supabase-studio
  template:
    metadata:
      labels:
        app: supabase-studio
    spec:
      containers:
        - name: studio
          image: supabase/studio:20240105-04-43
          env:
            - name: SUPABASE_URL
              value: http://localhost
            - name: SUPABASE_ANON_KEY
              value: your-anon-key
            - name: SUPABASE_SERVICE_KEY
              value: your-service-key
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: supabase-studio
  namespace: supabase
spec:
  selector:
    app: supabase-studio
  ports:
    - port: 3000
      targetPort: 3000
---
# REST API
apiVersion: apps/v1
kind: Deployment
metadata:
  name: supabase-rest
  namespace: supabase
spec:
  replicas: 1
  selector:
    matchLabels:
      app: supabase-rest
  template:
    metadata:
      labels:
        app: supabase-rest
    spec:
      containers:
        - name: rest
          image: postgrest/postgrest:v10.1.1
          env:
            - name: PGRST_DB_URI
              value: postgres://postgres:supersecret@supabase-postgres:5432/postgres
            - name: PGRST_DB_ANON_ROLE
              value: anon
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: supabase-rest
  namespace: supabase
spec:
  selector:
    app: supabase-rest
  ports:
    - port: 3000
      targetPort: 3000
